//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyExpense
    {
        public long DailyExpenseId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> TimeTypeId { get; set; }
        public Nullable<decimal> ConveyanceAmt { get; set; }
        public Nullable<decimal> FoodTeaExpense { get; set; }
        public Nullable<long> CustomerBranchId { get; set; }
        public Nullable<long> CompanyBranchId { get; set; }
        public string DailyExpenseStatus { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string DailyExpenseCode { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<System.DateTime> DailyExpenseDate { get; set; }
    }
}
