//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitShortName { get; set; }
        public int AllowDecimal { get; set; }
        public bool IsMultipleUnit { get; set; }
        public string UnitValue { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
